<template>
    <div>
        <div class="input-line square">
            Группа
            <input type="text" class="input rad-def" placeholder="Группа">
        </div>
        <div class="table-wrapper">
            <div class="table-header">
                dfgffgf
            </div>
            <table class="table">
                <thead>
                <tr>
                    <th>Имя</th>
                    <th>Группа</th>
                    <th>Тест</th>
                    <th>Оценка</th>
                    <th>Время</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                </tr>
                <tr>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                </tr>
                <tr>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                </tr>
                <tr>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                </tr>
                <tr>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                </tr>
                <tr>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                </tr>
                <tr>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                </tr>
                <tr>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                </tr>
                <tr>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                </tr>
                <tr>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                </tr>
                <tr>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                </tr>
                <tr>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                </tr>
                <tr>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                </tr>
                <tr>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                </tr>
                <tr>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                </tr>
                <tr>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                </tr>
                <tr>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                </tr>
                <tr>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                </tr>
                <tr>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                </tr>
                <tr>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                </tr>
                <tr>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                </tr>
                <tr>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                </tr>
                <tr>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                </tr>
                <tr>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                </tr>
                <tr>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                </tr>
                <tr>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                    <td>cvbcv</td>
                </tr>

                </tbody>
            </table>
        </div>
    </div>
</template>

<script>
  export default {
    name: 'AddStudentForm',
  };
</script>

<style scoped>

</style>